config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :admins, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only:[:index, :edit, :create, :update]
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :edit, :show, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  
  scope module: :public do
    root to: 'homes#top'
    get "home/about" =>"homes#about"
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :delete, :create]
    delete "cart_items/:id" =>"cart_items#destroy"
    delete "cart_items" =>"cart_items#destroy_all",as:"destroy_all"
    get "customers/confirm" =>"customers#confirm"
    patch "customers/withdraw" =>"customers#withdraw",as:"withdraw"
     resource :customer, only:[:show, :edit, :update]
    get "orders/complete" =>"orders#complete"
    resources :orders, only:[:new, :create, :index, :show]
    post "orders/confirm" =>"orders#confirm"
    resources :addresses, only:[:index, :edit, :update]
    post "addresses" =>"addresses#create"
    delete "addresses/:id" =>"addresses#destroy"
  end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :addresses   
  has_many :orders
  has_many :cart_items
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :telephone_number, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
   before_action :authenticate_admin!
  
  def index
   @customers = Customer.all
  end
  
  def show
   @customer = Customer.find(params[:id])
  end
  
  def edit
   @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
     flash[:notice] = "successfully" 
     redirect_to  admin_customers_path(@customer.id)
    else
      flash[:notice] = "error" 
      render :edit
    end
  end
  
  private
   
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kama, :first_name_kana, 
    :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customres::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
  
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customres::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customres::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  def after_sign_up_path_for(resource)
    items_path
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  # def new
  # @customer = Customer.new
  # end
  
  # def create
  #   @customer = Customer.new(customer_params)
  #   if @customer.save
  #     flash[:notice] = "successfully"
  #     redirect_to  items_path(@customer)
  #   else
  #     @customer = Customer.all
  #     render :index
  #   end
  # end
  
  private
   
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_inactive_customer, only: [:create]
  before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end
  def after_sign_in_path_for(resource)
    items_path
  end

  protected
  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    return if !@customer
    # if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_active
        redirect_to new_customer_session_path
      end
    # end
  end
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customres::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<p id="notice"></p>

<div class=container>
 <div class=row>
  <div class="px-3">
   <h4>
    <%= @customer.last_name + @customer.first_name %>
    の会員情報編集
    </h4>
    <%= form_with model:@customer, url: admin_customer_path(@customer.id), local:true,method: :patch do |f| %>
    <div class=group>
     <label for="id">会員ID
      <%= @customer.id %>
     </label>
    </div>
    <div class="form-group">
     <label for="name">氏名
     <%=f.text_field :last_name %>
     <%=f.text_field :first_name %>
     </label>
   </div>
   <div class="form-group">
    <label for="name_kana">フリガナ
      <%=f.text_field :last_name_kana %>
     <%=f.text_field :first_name_kana %>
    </label>
   </div>
   <div class="form-group">
     <label for="postal_code">郵便番号
      <%= f.text_field :postal_code %>
    </label>
   </div>
   <div class=form-group>
     <label for="address">住所
      <%= f.text_field :address, :size=>"60" %>
     </label>
   </div>
   <div class=form-group>
     <label for="telephone_number">電話番号
      <%=  f.text_field :telephone_number %>
     </label>
    </div>
   <div class=form-group>
     <label for="email">メールアドレス
      <%= f.text_field :email %>
     </label>
   </div>
   <div class=form-group>
     <label for="sale">会員ステータス
      <%= f.radio_button(:is_active, true) %>
      <%= f.label :is_active, "有効", style: "display: inline-block;" %>
      <%= f.radio_button(:is_active, false) %>
      <%= f.label :is_active, "退会", style: "display: inline-block;" %>
    </label>
   </div>
    <%=f.submit "変更を保存", class:'btn btn-success'  %>
    <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<p id="notice"></p>

<div class="container">
 <div class="row">
  <div class="px-3 mx-auto">
   <h4>会員一覧</h4>
　 <table class="table">
    <thead>
     <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
     </tr>
    </thead>
    <tbody>
　　<% @customers.each do |customer| %>
　　 <tr>
　　   <td><%= customer.id %></td>
　　   <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
　　   <td><%= customer.email %></td>
　　   <td>
　　    <% if customer.is_active %>
        <font color="green">有効</font>
        <% else %>
        <font color="gray">退会</font>
        <% end %>
      </td>
      </tr>
     <% end %>
     </div>
    </div>
  </div>
 </div>

app/views/admin/customers/show.html.erb
<p id="notice"></p>

<div class="container">  
 <div class="row">  
  <div class="px-3 mx-auto">
   <h4>
    <%= @customer.last_name + @customer.first_name %>
    の会員詳細
   </h4>
    <div class=group>
     <label for="id">会員
      <%= @customer.id %>
     </label>
    </div>
    <div class=group>
     <label for="name">氏名
      <%= @customer.last_name %>
      <%= @customer.first_name %>
     </label>
    </div>
    <div class=group>
     <label for="name_kana">フリガナ
      <%= @customer.last_name_kana %>
      <%= @customer.first_name_kana %>
     </label>
    </div>
    <div class=group>
     <label for="postal_code">郵便番号
      <%= @customer.postal_code %>
     </label>
    </div>
    <div class=group>
     <label for="address">住所
      <%= @customer.address %>
     </label>
    </div>
    <div class=group>
     <label for="telephone_number">電話番号
      <%= @customer.telephone_number %>
     </label>
    </div>
    <div class=group>
     <label for="email">メールアドレス
      <%= @customer.email %>
     </label>
    </div>
    <div class=group>
     <label for="is_active">会員ステータス
      <%if @customer.is_active %>
        <font color="green">有効</font>
      <% else %>
        <font color="gray">退会</font>
      <% end %>
     </label>
    </div>
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:'btn btn-success' %>
    <%= link_to "注文履歴一覧を見る", admin_root_path(@customer), class:'btn btn-primary' %>
    
  </div>
 </div>
</div>