config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :admins, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only:[:index, :edit, :create, :update]
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :edit, :show, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  
  scope module: :public do
    root to: 'homes#top'
    get "home/about" =>"homes#about"
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :delete, :create]
    delete "cart_items/:id" =>"cart_items#destroy"
    delete "cart_items" =>"cart_items#destroy_all",as:"destroy_all"
    get "customers/confirm" =>"customers#confirm"
    patch "customers/withdraw" =>"customers#withdraw",as:"withdraw"
     resource :customer, only:[:show, :edit, :update]
    get "orders/complete" =>"orders#complete"
    resources :orders, only:[:new, :create, :index, :show]
    post "orders/confirm" =>"orders#confirm"
    resources :addresses, only:[:index, :edit, :update]
    post "addresses" =>"addresses#create"
    delete "addresses/:id" =>"addresses#destroy"
  end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

 belongs_to :customer
 
 def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
 end

 validates :address, presence: true
 validates :postal_code, presence: true
 validates :name, presence: true
end

app/models/addresse.rb
class Addresse < ApplicationRecord
  
 validates :address, presence: true
 validates :postal_code, presence: true
 validates :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item, optional: true
  
  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true
  
 def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
  item.taxin_price*quantity
 end  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :addresses   
  has_many :orders
  has_many :cart_items
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  validates :name, presence: true
  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
 
 belongs_to :genre
 has_many :cart_items
 has_many :order_details

 attachment :image
 
 def add_tax_price
  (self.price * 1.1).round
 end
 

 
end

app/models/order.rb
class Order < ApplicationRecord
   
   has_many :order_detalis
   belongs_to :customer
   
   enum status: {
     wait_payment:0, confirm_payment:1, now_making:2, prepare_shipment:3, done_shipment:4
  }
  
  enum payment_method: {
    "クレジットカード":0 , "銀行振込":1 
  }
  
   validates :customer_id, presence: true
   validates :postal_code, presence: true
   validates :address, presence: true
   validates :name, presence: true
   validates :shipping_cost, presence: true
   validates :total_payment, presence: true
   validates :payment_method, presence: true
   validates :status, presence: true

end

app/models/order_detali.rb
class OrderDetali < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    not_stated:0, waiting_for_production:1, in_production:2,  completion_of_production:3
  }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def edit
   @genre = Genre.find(params[:id])
  end
  
  def create
   @genre = Genre.new(genre_params)
    if @genre.save
     flash[:notice] = "successfully"
     redirect_to admin_genres_path(@genre.id)
    else
     flash[:notice] = "error"
      @genres = Genre.all
      render :index
    end
  end
   
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     flash[:notice] = "successfully" 
     redirect_to admin_genres_path
    else
     flash[:notice] = "error" 
     render :edit
    end
  end
   
   private
   
   def genre_params
    params.require(:genre).permit(:name)
   end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
   @order = Order.new
   @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
  @item = Item.new
  @genres = Genre.all
  end
 
  def index
   @item = Item.new
   @items = Item.all
   @genre = Genre.new
  # @genres = @item.genre
  end
  
  def show
   @genre = Genre.new
   @item = Item.find(params[:id])
   @genres = @item.genre
  end
  
  def edit
   @item = Item.find(params[:id])
   @genres = Genre.all
   
  end
  def create
    @item = Item.new(item_params)
    if @item.save
       flash[:notice] = "successfully"
       redirect_to  admin_item_path(@item.id)
    else
      @items = Item.all
      render :index
    end  
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     flash[:notice] = "successfully" 
     redirect_to  admin_items_path(@item.id)
    else
      flash[:notice] = "error" 
      render :edit
    end
  end

 
  private
   
  def item_params
   params.require(:item).permit(:genre_id, :image, :name, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
   @order = Order.find(params[:id])
   @order_detalis = @order.order_detalis
   @total=0
   @order_detalis.each do |order_detail|
   @total += order_detail.item.price*order_detail.amount 
   end 
  end
  
  def update
    @order = Order.find(params[:id])
     if @order.update(order_params)
      if @order.status == "confirm_payment"
       p @order.order_detalis
       
       p "ty"
       
         @order.order_detalis.update_all(making_status: "waiting_for_production")
      end
     redirect_to  admin_order_path(@order.id)
     else
      render :show
     end 
  end
  
  private
   
  def order_params
   params.require(:order).permit(:status)
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  add_flash_types :success, :info, :warning, :danger
  
  
  
  def after_sign_out_path_for(resource)
    root_path(resource)
  end
  
  

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<p id="notice"></p>

<h4>ジャンル編集</h4>
<% if @genre.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> :</h2>
      <ul>
        <% @cart_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
     </div>
    <% end %>
<div class=container>
 <div class=row>
  <div class="px-3 mx-auto">
    <%= form_with model:@genre, url:"/admin/genres/#{@genre.id}", local:true,method: :patch do |f| %>
    <div class="form-group">
    <label for="name">ジャンル名</label>
    <%= f.text_field :name %>
   </div>
   <%=f.submit "変更を保存", class:'btn btn-success' %>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/genres/index.html.erb
<p id="notice"></p>
<h4>ジャンル一覧・追加</h4>

<div class=container>
 <div class=row>
  <div class="px-3 mx-auto">
   <%= form_with model: @genre, url:'/admin/genres', local:true do |f| %>
　　 <label for="name">ジャンル名</label>
     <%= f.text_field :name, :placeholder => "ジャンル名" %>
     <%=f.submit "新規登録", class:'btn btn-success' %>
   <% end %>
    <hr>
    <table class="table">
    <thead>
     <tr>
      <th>ジャンル</th>
     </tr>
    </thead>
    <tbody>
     <% @genres.each do |genre| %>
     <tr>
       <td><%= genre.name %></td>
       <td><%= link_to "編集", edit_admin_genre_path(genre.id), class:'btn btn-success' %></td>
     </tr>
     <% end %>
     </tbody>
   </table>
   </hr>
  </div>
 </div>
</div>

app/views/admin/items/edit.html.erb
<p id="notice"></p>
<div class=container>
 <div class=row>
  <div class="px-3 mx-auto">
   <h4>商品編集</h4>
    <%= form_with model:@item, url: admin_item_path, local:true,method: :patch do |f| %>
    <div class=form-group>
     <label for="Image_id">商品画像
      <%= f.attachment_field :image %>
     </label>
    </div>
    <div class="form-group">
     <label for="name">商品名
     <%= f.text_field :name %>
     </label>
   </div>
   <div class="form-group">
    <label for="name">商品説明
    <%= f.text_area :introduction %>
    </label>
   </div>
   <div class="form-group">
    <label for="name">ジャンル
    <%= f.collection_select :genre_id, @genres, :id, :name %>
    </label>
   </div>
   <div class=form-group>
     <label for="price">税抜価格
      <%= f.text_field :price %>円
     </label>
   </div>
   <div class=form-group>
     <label for="sale">販売ステータス
      <%= f.radio_button(:is_active, true) %>
      <%= f.label :is_active, "販売中", style: "display: inline-block;" %>
      <%= f.radio_button(:is_active, false) %>
      <%= f.label :is_active, "販売停止中", style: "display: inline-block;" %>
    </label>
   </div>
   <div class="text-center">
    <%=f.submit "変更を保存", class:'btn btn-success' %>
    <% end %>
   </div>
  </div>
 </div>
</div>

app/views/admin/items/index.html.erb
<p id="notice"></p>
<div class="container">
 <div class="row">
  <div class="px-1">
   <%= link_to new_admin_item_path(@item), class:'fas fa-plus-circle fa-4x' do %>
   <% end %>
   <h4>商品一覧</h4>
　 <table class="table">
    <thead>
     <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
     </tr>
    </thead>
    <tbody>
　　<% @items.each do |item| %>
　　 <tr>
　　   <td><%= item.id %></td>
　　   <td><%= link_to item.name, admin_item_path(item.id) %></td>
　　   <td><%= item.price %></td>
　　   <td><%= item.genre.name %></td>
　　   <td>
　　    <% if item.is_active %>
　　     <font color="green">販売中</font>
　　    <% else %>
　　     <font color="red">販売停止中</font>
　　    <% end %>
　　   </td>
      </tr>
     <% end %>
     </tbody>
   </table>
     <div class="pagination">
          <p>1</p>
          <p>2</p>
          <p>3</p>
          <p>Next></p>
          <p></p>
          <p>Last>></p>
     </div>
    </div>
  </div>
 </div>

app/views/admin/items/new.html.erb
<p id="notice"></p>
<div class=container>
 <div class=row>
  <div class="px-3 mx-auto">
   <h4>商品新規登録</h4>
    <%= form_with model: @item, url: "/admin/items",method: :post, local:true do |f| %>
    <div class=form-group>
     <label for="Image_id">商品画像
      <%= f.attachment_field :image %>
     </label>
    </div>
    <div class=form-group>
     <label for="name">商品名
      <%=f.text_field :name, :placeholder => "商品名" %>
     </label>
    </div>
    <div class=form-group>
     <label for="introduction">商品説明
      <textarea cols="30" rows="5"placeholder="ここに説明文を記述します"></textarea>
     </label>
    </div>
    <div class=form-group>
     <label for="name">ジャンル
       <%= f.collection_select :genre_id, @genres, :id, :name, "--選択してください--" => "--選択してください--" %>
     </label>
    </div>
    <div class=form-group>
     <label for="item_name">税抜価格
      <%=f.text_field :price, :placeholder =>"1000" %>円
     </label>
    </div>
    <div class=form-group>
     <label for="sale">販売ステータス
      <%= f.radio_button(:is_active, true) %>
      <%= f.label :is_active, "販売中", style: "display: inline-block;" %>
      <%= f.radio_button(:is_active, false) %>
      <%= f.label :is_active, "販売停止中", style: "display: inline-block;" %>
     </label>
    </div>
     <div class="text-center">
     <%=f.submit "新規登録", class:'btn btn-success'  %>
     <% end %>
   </div>
 </div>
</div>

app/views/admin/items/show.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">  
 <div class="row">  
  <div class="col-md-3">
    <h4>商品詳細</h4>
    <%= attachment_image_tag @item, :image, :size =>'400x100', fallback: "image.png" %>
  </div>
  <div class="col-md-8 offset-md-1">
    <div class=group>
     <label for="name">商品名
      <%= @item.name %>
     </label>
    </div>
    <div class=group>
     <label for="installation">商品説明
      <%= @item.introduction %>
     </label>
    </div>
    <div class=group>
     <label for="genre">ジャンル
      <%= @item.genre.name %>
     </label>
    </div>
    <div class=group>
     <label for="name">税込価格（税抜価格）
      <%= @item.add_tax_price %> 円
       (<%= @item.price %>)円
     </label>
    </div>
    <div class=group>
     <label for="is_active">販売ステータス
      <td>
      <% if @item.is_active %>
       <font color="green"> 販売中</font>
      <% else %>
       <font color="red">販売停止中</font>
      <% end %>
      </td>
     </label>
    </div>
    <div class=group>
    <%= link_to "編集する", edit_admin_item_path(@item.id), class:'btn btn-success' %>
    </div>
  </div>
 </div>
</div>

app/views/admin/orders/show.html.erb
<p id="notice"></p>
<div class="container">  
 <div class="row">  
  <div class="px-8">
   <h4>注文履歴詳細</h4>
   <h4>登録情報</h4>
   <table class="table">
    <tr>
     <th>購入者</th>
      <td><%= @order.name %></td>
    </tr>
    <tr>
     <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
     <th>配送先</th>
     <td><%= @order.address %></td>
  　 </tr>
  　 <tr>
  　  <th>支払方法</th>
     <td><%= @order.payment_method %></td>
  　 </tr>
  　 <tr>
       <th>注文ステータス</th>
       <td>
       <%= form_with model: @order, url: admin_order_path(@order), local:true do |f| %>

         <%= f.select :status, Order.statuses_i18n.invert %>

           <%= f.submit "更新" , class:'btn btn- btn-success' %>
       <% end %>
         
       </td>
    </tr>
   </table>
   <table class="table">
    <thead>
      <tr>
       <th>商品名</th>
       <th>単価(税込)</th>
       <th>個数</th>
       <th>小計</th>
       <th>製造ステータス</th>
      </tr>
    </thead>
    <tbody>
     <% @order_detalis.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td> <%= order_detail.item.price %></td>
        <td><%= order_detail.amount %></td>
        <td><%= order_detail.item.price*order_detail.amount %></td>
        <td>
         <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), local:true do |f| %>
           <%= f.select :making_status, OrderDetali.making_statuses_i18n.invert %>
           <%= f.submit "更新" , class:'btn btn- btn-success' %>
         <% end %>
        </td>
      </tr>
     <% end %>
    </tbody>
   </table>
  </div>
  <div class="col-md-3 offset-md-8">
   <table class="table">
    <tr>
     <th>商品合計</th>
     <td><%= @total %>円</td>
    </tr>
    <tr>
     <th>送料</th>
     <td><%= @order.shipping_cost %>円</td>
    </tr>
    <tr>
     <th>請求金額合計</th>
     <td><%= @order.total_payment %>円</td>
    </tr>
   </table>
  </div>
 </div>
</div>