config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_for :admins, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :genres, only:[:index, :edit, :create, :update]
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :edit, :show, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  
  scope module: :public do
    root to: 'homes#top'
    get "home/about" =>"homes#about"
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :delete, :create]
    delete "cart_items/:id" =>"cart_items#destroy"
    delete "cart_items" =>"cart_items#destroy_all",as:"destroy_all"
    get "customers/confirm" =>"customers#confirm"
    patch "customers/withdraw" =>"customers#withdraw",as:"withdraw"
     resource :customer, only:[:show, :edit, :update]
    get "orders/complete" =>"orders#complete"
    resources :orders, only:[:new, :create, :index, :show]
    post "orders/confirm" =>"orders#confirm"
    resources :addresses, only:[:index, :edit, :update]
    post "addresses" =>"addresses#create"
    delete "addresses/:id" =>"addresses#destroy"
  end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

 belongs_to :customer
 
 def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
 end

 validates :address, presence: true
 validates :postal_code, presence: true
 validates :name, presence: true
end

app/models/addresse.rb
class Addresse < ApplicationRecord
  
 validates :address, presence: true
 validates :postal_code, presence: true
 validates :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item, optional: true
  
  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true
  
 def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
  item.taxin_price*quantity
 end  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :addresses   
  has_many :orders
  has_many :cart_items
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :telephone_number, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  validates :name, presence: true
  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
 
 belongs_to :genre
 has_many :cart_items
 has_many :order_details

 attachment :image
 
 def add_tax_price
  (self.price * 1.1).round
 end
 

 
end

app/models/order.rb
class Order < ApplicationRecord
   
   has_many :order_detalis
   belongs_to :customer
   
   enum status: {
     wait_payment:0, confirm_payment:1, now_making:2, prepare_shipment:3, done_shipment:4
  }
  
  enum payment_method: {
    "クレジットカード":0 , "銀行振込":1 
  }
  
   validates :customer_id, presence: true
   validates :postal_code, presence: true
   validates :address, presence: true
   validates :name, presence: true
   validates :shipping_cost, presence: true
   validates :total_payment, presence: true
   validates :payment_method, presence: true
   validates :status, presence: true

end

app/models/order_detali.rb
class OrderDetali < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    not_stated:0, waiting_for_production:1, in_production:2,  completion_of_production:3
  }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
   @order = Order.new
   @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
  @item = Item.new
  @genres = Genre.all
  end
 
  def index
   @item = Item.new
   @items = Item.all
   @genre = Genre.new
  # @genres = @item.genre
  end
  
  def show
   @genre = Genre.new
   @item = Item.find(params[:id])
   @genres = @item.genre
  end
  
  def edit
   @item = Item.find(params[:id])
   @genres = Genre.all
   
  end
  def create
    @item = Item.new(item_params)
    if @item.save
       flash[:notice] = "successfully"
       redirect_to  admin_item_path(@item.id)
    else
      @items = Item.all
      render :index
    end  
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     flash[:notice] = "successfully" 
     redirect_to  admin_items_path(@item.id)
    else
      flash[:notice] = "error" 
      render :edit
    end
  end

 
  private
   
  def item_params
   params.require(:item).permit(:genre_id, :image, :name, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  add_flash_types :success, :info, :warning, :danger
  
  
  
  def after_sign_out_path_for(resource)
    root_path(resource)
  end
  
  

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
</html>
<meta charset="UTF-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
 <header>
 <header>
  <nav class="navbar navbar-expand-lg navbar-liget bg-light">
    <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
         ようこそ<%= current_customer.last_name %>さん！
        <li class="nav-item">
          <%= link_to "マイページ", customer_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", cart_items_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:'btn btn-outline-dark' %>
        </li>
        <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "商品一覧", admin_items_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
         <%= link_to "会員一覧", admin_customers_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "注文履歴一覧", admin_root_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "ジャンル一覧", admin_genres_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'btn btn-outline-dark'  %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "About", home_about_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
        <%= link_to "商品一覧", items_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
        <%= link_to "新規登録", new_customer_registration_path, class:'btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
        <%= link_to "ログイン", new_customer_session_path, class:'btn btn-outline-dark' %>
        </li>
        <% end %>
        </ul>
       </div>
     </div>
    </nav>
   </header>
   <main>
     <%= yield %>
   </main>
  </body>
</html>